---
# The chart to use
azimuth_caas_operator_chart_repo: https://stackhpc.github.io/azimuth-caas-operator
azimuth_caas_operator_chart_name: azimuth-caas-operator
azimuth_caas_operator_chart_version: "0.1.2"

# Release information for the operator release
# Use the same namespace as Azimuth by default
azimuth_caas_operator_release_namespace: "{{ azimuth_release_namespace | default('azimuth') }}"
azimuth_caas_operator_release_name: azimuth-caas-operator

# The timeout to wait for CAPI operator to become ready
azimuth_caas_operator_wait_timeout: 5m

# TODO: needs to configure some env vars for the operato
azimuth_caas_operator_release_values: {}

#
# Workstation
#
# Gacamole based "bigger laptop"
azimuth_caas_crd_workstation_enabled: true
# The ID of the image for use with the StackHPC workstation
# By default, use the workstation image from community images if available
azimuth_caas_crd_workstation_image: >-
  {{-
    (
      community_images_image_ids.workstation_20221017_1036
      if (
        community_images_image_ids is defined and
        'workstation_20221017_1036' in community_images_image_ids
      )
      else undef(hint = 'azimuth_caas_crd_workstation_image is required')
    )
    if azimuth_caas_crd_workstation_enabled
    else None
  }}

# TODO: move to a tag, reference in the updated images!
azimuth_caas_crd_workstation_git_version: d3abe67b0583e09daeed5d6b1e8686ef66d95da5
azimuth_caas_crd_workstation_template:
  gitUrl: "https://github.com/stackhpc/caas-workstation.git"
  gitVersion: "{{ azimuth_caas_crd_workstation_git_version }}"
  uiMetaUrl: "https://raw.githubusercontent.com/stackhpc/caas-workstation/{{ azimuth_caas_stackhpc_workstation_git_version }}/ui-meta/workstation.yml"
  playbook: "workstation.yml"
  extraVars:
    cluster_image: "{{ azimuth_caas_crd_workstation_image }}"

#
# Quick Test
#
# This runs ansible that does nothing
# except check the CRD mechanisms work,
# including the auto delete feature.

# TODO: make this false!
azimuth_caas_crd_quicktest_enable: true
azimuth_caas_crd_quicktest_template:
  uiMetaUrl: "https://raw.githubusercontent.com/stackhpc/azimuth-caas-operator/d977b04df85d7492ba726daf249709731130e6cf/tools/ui_meta_quick_test.yaml"
  gitUrl: "https://github.com/ansible/ansible-runner"
  gitVersion: "devel"
  playbook: "demo/project/test.yml"
  extraVars:
    foo: "bar"

# TODO: add more appliances in here

# TODO: no support for deleting items in here right now
azimuth_caas_operator_cluster_templates_default:
  workstation: "{{ azimuth_caas_crd_workstation_template if azimuth_caas_crd_workstation_enabled else None }}"
  quicktest: "{{ azimuth_caas_crd_quicktest_template if azimuth_caas_crd_quicktest_enable else None }}"

azimuth_caas_operator_cluster_templates_overrides: {}

azimuth_caas_operator_cluster_templates: >-
  {{-
    azimuth_caas_operator_cluster_templates_default |
      combine(azimuth_caas_operator_cluster_templates_overrides, recursive = True)
  }}
