---

- name: Install Consul on target Kubernetes cluster
  kubernetes.core.helm:
    chart_ref: "{{ consul_chart_name }}"
    chart_repo_url: "{{ consul_chart_repo }}"
    chart_version: "{{ consul_chart_version }}"
    release_namespace: "{{ consul_release_namespace }}"
    release_name: "{{ consul_release_name }}"
    release_values: "{{ consul_release_values }}"
    atomic: yes
    create_namespace: yes
    wait: yes
    wait_timeout: "{{ consul_wait_timeout }}"

- name: Get Consul service information
  command: >-
    kubectl get service
      --namespace {{ consul_release_namespace }}
      --selector {{ consul_server_service_selector }}
      --output json
  register: consul_services_cmd
  vars:
    consul_server_service_selector: "app={{ consul_release_name }},component=server"

- name: Set Consul server service fact
  set_fact:
    consul_server_service: "{{ (consul_services_cmd.stdout | from_json)['items'] | first }}"

- name: Set Consul server facts
  set_fact:
    consul_server_host: >-
      {{-
        consul_server_host
        if consul_server_host is defined
        else (
          "{}.{}".format(
            consul_server_service.metadata.name,
            consul_server_service.metadata.namespace
          )
        )
      }}
    consul_server_port: >-
      {{-
        consul_server_port
        if consul_server_port is defined
        else (
          consul_server_service.spec.ports |
            selectattr('name', 'equalto', 'http') |
            map(attribute = 'port') |
            first
        )
      }}


- block:

  - name: Ensure kubernetes python client is available
    ansible.builtin.pip:
      state: present
      name: kubernetes

  - name: Ensure Consul ServiceMonitor is present on cluster
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: monitoring.coreos.com/v1
        kind: ServiceMonitor
        metadata:
          labels:
            release: kube-prometheus-stack
          name: consul
          namespace: azimuth
        spec:
          endpoints:
          - port: http
            path: /v1/agent/metrics
          namespaceSelector:
            matchNames:
            - azimuth
          selector:
            matchLabels:
              # Labels should match cluster's consul-server service
              app.kubernetes.io/managed-by: Helm
              app: consul
              chart: consul-helm
              component: server
              heritage: Helm
              release: consul

  - name: Ensure ConfigMap containing Grafana dashboard is present
    kubernetes.core.k8s:
      state: present
      definition:
        kind: ConfigMap
        metadata:
          labels:
            grafana_dashboard: "1"
            release: kube-prometheus-stack
          name: consul-grafana-dashboard
          namespace: azimuth
        data:
          consul_dashboard.json:
            "{{ lookup('file', 'grafana_dashboard.json' ) | from_json | to_nice_json }}"

  when: azimuth_management_cluster_monitoring_enabled
