namespace: stackhpc
name: capi_manager
version: 0.1.0
description: Roles and playbooks for deploying the Kuberetes Cluster API manager.
readme: README.md
authors:
  - "Matt Pryor <matt@stackhpc.com>"
repository: https://github.com/stackhpc/ansible-collection-capi-manager

dependencies:
  ansible.posix: "*"
  community.general: "*"
