collections:
  - name: ansible.posix
    version: "*"
  - name: community.general
    version: "*"

roles:
  - name: stackhpc.terraform-infra
    src: https://github.com/stackhpc/ansible-role-terraform-infra.git
    version: 032ca5d051c8979d1edc4a457c19f9fad4d1d07a
