---

- name: Include precheck tasks
  ansible.builtin.include_tasks:
    file: prechecks.yml

- name: Ensure kube-prometheus-stack is installed on target Kubernetes cluster
  kubernetes.core.helm:
    chart_ref: "{{ kube_prometheus_chart_name }}"
    chart_repo_url: "{{ kube_prometheus_chart_repo }}"
    chart_version: "{{ kube_prometheus_chart_version }}"
    release_namespace: "{{ kube_prometheus_release_namespace }}"
    release_name: "{{ kube_prometheus_release_name }}"
    release_values: "{{ kube_prometheus_release_values }}"
    atomic: yes
    create_namespace: yes
