---

- name: Fail when required vars are not defined
  fail:
    msg: "{{ item }} must be defined when kube_prometheus_stack_alertmanager_slack_alerts is true"
  when: 
    - kube_prometheus_stack_alertmanager_slack_alerts
    - item is undefined
  loop:
    - "{{ kube_prometheus_stack_alertmanager_slack_url }}"
    - "{{ kube_prometheus_stack_alertmanager_slack_channel }}"
  loop_control:
    index_var: idx
    label: "{{ idx }}"