---

- name: Make kustomization directory
  file:
    path: "{{ clusterapi_kustomization_directory }}"
    state: directory

- name: Write kustomization file
  copy:
    content: "{{ clusterapi_kustomization | to_nice_yaml }}"
    dest: "{{ clusterapi_kustomization_directory }}/kustomization.yaml"

- name: Install Cluster API resources
  command: kubectl apply -k {{ clusterapi_kustomization_directory }}

- name: Wait for Cluster API controllers to become ready
  command: >-
    kubectl wait
      --for=condition={{ watch.condition }}
      --namespace {{ watch.namespace }}
      --timeout 0s
      {{ watch.kind }}/{{ watch.name }}
  changed_when: false
  register: clusterapi_controller_wait
  until: clusterapi_controller_wait is succeeded
  retries: 60
  delay: 10
  loop: "{{ clusterapi_watches }}"
  loop_control:
    loop_var: watch
    label: "{{ watch.namespace }}/{{ watch.kind }}/{{ watch.name }}"
