---

- include_tasks: upload_image.yml
  vars:
    community_images_image_spec: "{{ item.value }}"

- name: "Store image ID - {{ item.value.name }}"
  set_fact:
    community_images_image_ids: >-
      {{-
        community_images_image_ids |
          default({}) |
          combine({ item.key: community_images_image_id })
      }}
