---

- name: Create Azimuth release namespace
  command: kubectl create namespace {{ azimuth_release_namespace }}
  register: azimuth_create_namespace
  changed_when: azimuth_create_namespace.rc == 0
  failed_when: >-
    azimuth_create_namespace.rc != 0 and
    'AlreadyExists' not in azimuth_create_namespace.stderr

- name: Install trust bundle
  command: kubectl apply -f -
  args:
    stdin: "{{ azimuth_trust_bundle_configmap_definition | to_nice_yaml }}"
  vars:
    azimuth_trust_bundle_configmap_definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ azimuth_trust_bundle_configmap_name }}"
        namespace: "{{ azimuth_release_namespace }}"
      data:
        ca-certificates.crt: "{{ azimuth_trust_bundle }}"
  when: azimuth_trust_bundle

- name: Install Azimuth on target Kubernetes cluster
  kubernetes.core.helm:
    chart_ref: "{{ azimuth_chart_name }}"
    chart_repo_url: "{{ azimuth_chart_repo }}"
    chart_version: "{{ azimuth_chart_version }}"
    release_namespace: "{{ azimuth_release_namespace }}"
    release_name: "{{ azimuth_release_name }}"
    release_values: "{{ azimuth_release_values }}"
    atomic: yes
    create_namespace: yes
    wait: yes
    wait_timeout: "{{ azimuth_wait_timeout }}"
