---

- name: Install Azimuth on target Kubernetes cluster
  kubernetes.core.helm:
    chart_ref: "{{ azimuth_chart_name }}"
    chart_repo_url: "{{ azimuth_chart_repo }}"
    chart_version: "{{ azimuth_chart_version }}"
    release_namespace: "{{ azimuth_release_namespace }}"
    release_name: "{{ azimuth_release_name }}"
    release_values: "{{ azimuth_release_values }}"
    atomic: yes
    create_namespace: yes
    wait: yes
    wait_timeout: "{{ azimuth_wait_timeout }}"
