---

- name: Ensure bin directory exists
  file:
    path: "{{ kubectl_bin_directory }}"
    state: directory

- name: Download and install kubectl binary
  get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ (kubectl_bin_directory, 'kubectl') | path_join }}"
    mode: u=rwx,g=rx,o=rx
    force: yes
