---

# The chart to use
consul_chart_repo: https://helm.releases.hashicorp.com
consul_chart_name: consul
consul_chart_version: ~0.35.0

# Release information for the Consul release
consul_release_namespace: consul
consul_release_name: consul

# The timeout to wait for Consul to become ready
consul_wait_timeout: 10m

# The values for the release
consul_release_defaults:
  fullnameOverride: "{{ consul_release_name }}"
consul_release_overrides: {}
consul_release_values: >-
  {{-
    consul_release_defaults |
      combine(consul_release_overrides, recursive = True)
  }}
