---

clusterctl_version: v1.1.2
clusterctl_binary_url: https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ clusterctl_version }}/clusterctl-linux-amd64

# If empty, the default providers for each will be used
capi_core_provider:
capi_bootstrap_providers: []
capi_control_plane_providers: []
# By default, deploy the openstack infrastructure provider
capi_infrastructure_providers: [openstack]

# The target contract version
capi_contract_version: v1beta1

# The kubectl executable to use
kubectl_executable: kubectl
