---

kubectl_executable: kubectl

clusterctl_version: v0.4.4
clusterctl_binary_url: https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ clusterctl_version }}/clusterctl-linux-amd64

# If empty, the default providers for each will be used
capi_core_provider:
capi_bootstrap_providers: []
capi_control_plane_providers: []
capi_infrastructure_providers: []
