---

# The version and manifest URL for the Cluster API core components
clusterapi_core_version: v1.1.3
clusterapi_core_components: https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ clusterapi_core_version }}/cluster-api-components.yaml

# The version and manifest URL for the Cluster API OpenStack provider components
# FIXME: Until our patches are merged, use the StackHPC fork of the CAPO provider
clusterapi_openstack_version: v0.6.3-stackhpc.1
clusterapi_openstack_components: https://github.com/stackhpc/cluster-api-provider-openstack/releases/download/{{ clusterapi_openstack_version }}/infrastructure-components.yaml

# List of Cluster API component manifests to install
clusterapi_manifests:
  - "{{ clusterapi_core_components }}"
  - "{{ clusterapi_openstack_components }}"

# List of patches to apply to the resources in the manifests
clusterapi_patches:
  # The manifests contain environment variable substitutions for feature gates that we do not need
  - patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/args/2
    target:
      kind: Deployment
      namespace: capi-system
      name: capi-controller-manager
  - patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/args/2
    target:
      kind: Deployment
      namespace: capi-kubeadm-bootstrap-system
      name: capi-kubeadm-bootstrap-controller-manager
  - patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/args/2
    target:
      kind: Deployment
      namespace: capi-kubeadm-control-plane-system
      name: capi-kubeadm-control-plane-controller-manager

# The kustomization to use for Cluster API
clusterapi_kustomization:
  resources: "{{ clusterapi_manifests }}"
  patches: "{{ clusterapi_patches }}"

# Use a directory in $HOME for the kustomization by default
clusterapi_kustomization_directory: "{{ (ansible_env.HOME, 'clusterapi') | path_join }}"

# List of resources to watch for completeness
clusterapi_watches:
  - kind: deployment
    namespace: capi-system
    name: capi-controller-manager
    condition: Available
  - kind: deployment
    namespace: capi-kubeadm-bootstrap-system
    name: capi-kubeadm-bootstrap-controller-manager
    condition: Available
  - kind: deployment
    namespace: capi-kubeadm-control-plane-system
    name: capi-kubeadm-control-plane-controller-manager
    condition: Available
  - kind: deployment
    namespace: capo-system
    name: capo-controller-manager
    condition: Available
