---

- name: Install Terraform
  include_role:
    name: stackhpc.terraform.install

- block:
    - name: Upload infra image
      include_role:
        name: stackhpc.azimuth_ops.community_images
        tasks_from: upload_image
      vars:
        community_images_image_spec:
          name: "{{ infra_image_name }}"
          source_url: "{{ infra_image_source_url }}"
          source_disk_format: "{{ infra_image_source_disk_format }}"
          container_format: "{{ infra_image_container_format }}"
          visibility: private

    - name: Set infra image ID fact
      set_fact:
        infra_image_id: "{{ community_images_image_id }}"
  when: not infra_image_id

- name: Make Terraform project directory
  file:
    path: "{{ terraform_project_path }}"
    state: directory

- name: Write backend configuration
  copy:
    content: |
      terraform {
        backend "{{ terraform_backend_type }}" { }
      }
    dest: "{{ terraform_project_path }}/backend.tf"

- name: Template Terraform files into project directory
  template:
    src: "{{ item }}.j2"
    dest: "{{ terraform_project_path }}/{{ item }}"
  loop:
    - outputs.tf
    - providers.tf
    - resources.tf

- name: Provision infrastructure
  include_role:
    name: stackhpc.terraform.infra
