---

# The namespace that AWX should be deployed into
# Azimuth needs to access AWX secrets, so put it in the azimuth namespace by default
awx_namespace: "{{ azimuth_release_namespace | default('azimuth') }}"

# The URL and version of the AWX operator
awx_operator_repo_url: https://github.com/ansible/awx-operator.git
awx_operator_version: 0.16.0  # This should point to a tag
# The directory into which the AWX operator should be cloned
awx_operator_directory: /opt/awx-operator

# The registry to use for the AWX operator controller image
awx_operator_image_registry: quay.io/ansible/awx-operator
# The image to use for the AWX operator controller
awx_operator_image: "{{ awx_operator_image_registry }}:{{ awx_operator_version }}"

# The admin password for the AWX instance
awx_admin_password: "{{ undef(hint = 'awx_admin_password is required') }}"

# The name for the AWX instance
awx_name: awx

# The labels for the AWX instance
awx_labels:
  app.kubernetes.io/managed-by: ansible-collection-azimuth-ops
  app.kubernetes.io/instance: "{{ awx_name }}"

# The spec for the AWX instance
awx_spec_defaults:
  service_type: ClusterIP
  ingress_type: none
  create_preload_data: false
  garbage_collect_secrets: true
awx_spec_overrides: {}
awx_spec: "{{ awx_spec_defaults | combine(awx_spec_overrides, recursive = True) }}"
