---

k3s_version: v1.23.13+k3s1
k3s_binary_url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s
k3s_binary_checksum: sha256:334b42a96a65d7e54555827ca31f80896bf18978952f5aa5b8bb83bfdff3db0b

# Settings for an additional block device that will hold the k3s state, if present
k3s_storage_device: /dev/sdb
k3s_storage_fstype: xfs

# Indicates if the Traefik ingress controller should be enabled
k3s_traefik_enabled: false

# Bundle of certificates that should be added to the system trustroots
# E.g. if using a registry with a custom CA chain
k3s_trust_bundle: "{{ trust_bundle | default({}) }}"
