---

k3s_version: v1.21.3+k3s1
k3s_binary_url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s
k3s_binary_checksum: sha256:c257e119158feee992dc4397be00490103f0dde5af4b014e8d0f17f9db35ef00

# Settings for an additional block device that will hold the k3s state, if present
k3s_storage_device: /dev/sdb
k3s_storage_fstype: xfs
