---

- hosts: all
  become: yes
  collections:
    - stackhpc.capi_manager
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  vars:
    kubectl_executable: "k3s kubectl"
  roles:
    - k3s
    - clusterapi
