#####
# This playbook deploys the portal onto an existing Kubernetes cluster
#####

- hosts: azimuth_deploy
  roles:
    - role: stackhpc.azimuth_ops.certmanager
      when: certmanager_enabled
    - role: stackhpc.azimuth_ops.harbor
      when: harbor_enabled
    - role: stackhpc.azimuth_ops.clusterapi
      when: azimuth_kubernetes_enabled
    - role: stackhpc.azimuth_ops.awx
      when: azimuth_clusters_enabled
    - role: stackhpc.azimuth_ops.consul
      when: azimuth_apps_enabled or azimuth_clusters_enabled
    - role: stackhpc.azimuth_ops.zenith
      when: azimuth_apps_enabled
    - role: stackhpc.azimuth_ops.azimuth_capi_operator
      when: azimuth_kubernetes_enabled
    - stackhpc.azimuth_ops.azimuth
