---

# First, run the infra playbook in forward mode to populate the inventory
- import_playbook: stackhpc.capi_manager.infra

# Next, run the clusters playbook in teardown mode
- import_playbook: stackhpc.capi_manager.clusters
  vars:
    cluster_state_default: absent

# Finally, run the infra playbook in teardown mode to destroy the CAPI manager
- import_playbook: stackhpc.capi_manager.infra
  vars:
    terraform_state: absent
