#####
# This playbook uses Terraform to provision a single-node k3s cluster into which Azimuth
# and all it's dependencies are installed
#####


# Provision the K3S cluster
- import_playbook: stackhpc.azimuth_ops.k3s


# Install the NGINX ingress controller on the K3S cluster
- hosts: azimuth_deploy
  roles:
    - stackhpc.azimuth_ops.ingress_nginx


# Install Azimuth onto the node
- import_playbook: stackhpc.azimuth_ops.deploy
