---

# The directory into which images will be downloaded / converted
# If not given, a temporary directory will be used
community_images_workdir:

# OpenStack credentials for uploading images
#   The value of the OS_CLOUD environment variable to use
community_images_os_cloud: >-
  {{-
    lookup(
      'env',
      'OS_CLOUD',
      default = undef(hint = 'OS_CLOUD is not set')
    )
  }}
#   This is the local path to the application credential
community_images_os_clouds_file_local: >-
  {{-
    lookup(
      'env',
      'OS_CLIENT_CONFIG_FILE',
      default = undef(hint = 'OS_CLIENT_CONFIG_FILE is not set')
    )
  }}
#   The directory/path to upload the clouds.yaml to
community_images_os_config_dir: "{{ ansible_env.HOME }}/.config/openstack"
community_images_os_clouds_file: "{{ community_images_os_config_dir }}/clouds.yaml"

# The disk format for the target cloud
community_images_disk_format: qcow2

# The default community images to upload
# By default, we upload images for Kubernetes and CaaS appliances
# Slurm images are published by the slurm_image_builder repo - https://github.com/stackhpc/slurm_image_builder
# All other images are published by the azimuth-images repo - https://github.com/stackhpc/azimuth-images
# Images are hosted by UoC Arcus
community_images_base_url: https://object.arcus.openstack.hpc.cam.ac.uk/swift/v1/AUTH_f0dc9cb312144d0aa44037c9149d2513/azimuth-images-prerelease
community_images_slurm_base_url: https://object.arcus.openstack.hpc.cam.ac.uk/swift/v1/AUTH_3a06571936a0424bb40bc5c672c4ccb1/openhpc-images
community_images_default:
  # Images for Kubernetes
  kube_1_23_16:
    name: ubuntu-focal-kube-v1.23.16-230411-1334
    source_url: "{{ community_images_base_url }}/ubuntu-focal-kube-v1.23.16-230411-1334.qcow2"
    source_disk_format: qcow2
    container_format: bare
  kube_1_24_12:
    name: ubuntu-focal-kube-v1.24.12-230411-1402
    source_url: "{{ community_images_base_url }}/ubuntu-focal-kube-v1.24.12-230411-1402.qcow2"
    source_disk_format: qcow2
    container_format: bare
  kube_1_25_8:
    name: ubuntu-focal-kube-v1.25.8-230411-1429
    source_url: "{{ community_images_base_url }}/ubuntu-focal-kube-v1.25.8-230411-1429.qcow2"
    source_disk_format: qcow2
    container_format: bare
  kube_1_26_3:
    name: ubuntu-focal-kube-v1.26.3-230411-1504
    source_url: "{{ community_images_base_url }}/ubuntu-focal-kube-v1.26.3-230411-1504.qcow2"
    source_disk_format: qcow2
    container_format: bare
  # Images for CaaS appliances
  repo2docker:
    name: ubuntu-focal-jupyter-repo2docker-230411-1311
    source_url: "{{ community_images_base_url }}/ubuntu-focal-jupyter-repo2docker-230411-1311.qcow2"
    source_disk_format: qcow2
    container_format: bare
  workstation:
    name: ubuntu-focal-desktop-230411-1203
    source_url: "{{ community_images_base_url }}/ubuntu-focal-desktop-230411-1203.qcow2"
    source_disk_format: qcow2
    container_format: bare
  openhpc:
    name: openhpc-230217-1440
    source_url: "{{ community_images_slurm_base_url }}/openhpc-230217-1440.qcow2"
    source_disk_format: qcow2
    container_format: bare

# Any extra community images to upload as well as the defaults
community_images_extra: {}
  # # The key for the image, used to refer to the image ID elsewhere in Ansible variables
  # ubuntu_2004_20220411:
  #   # The name of the image
  #   name: Ubuntu-Focal-20.04-20220411
  #   # The source URL for the image
  #   source_url: https://cloud-images.ubuntu.com/focal/20220411/focal-server-cloudimg-amd64.img
  #   # The disk format of the image source
  #   source_disk_format: qcow2
  #   # The container format for the image
  #   container_format: bare

# The full set of community images to upload to the Azimuth project
community_images: >-
  {{ community_images_default | combine(community_images_extra, recursive = True) }}

# The default visibility for images
# Can be overridden on a per-image basis if required
community_images_default_visibility: community
# Indicates whether the visibility should be updated for pre-existing images
community_images_update_existing_visibility: true

# Any custom properties to set on community images
# Should be a list of strings in the format "key=value"
community_images_custom_properties: []

# The projects to explicitly share images with
# Only used if the default visibility is set to shared
community_images_share_projects: []
  # - key: "key of credential in clouds.yaml to use to accept the images"
  #   id: "id of project"
